---
# tasks file for myubunturole
- name: install tomcat
  apt:
   name: tomcat8
   state: present
- name: tomcat8 status
  service: 
   name: tomcat8
   state: present

- name: Go to the folder and execute command
  command: chdir= /var/lib/tomcat8/conf
  
- name:  copy tom config file into all nodes
  template:
   src:  templates/mytomconfig.j2
   dest: /usr/share/tomcat/conf/tomcat.conf
  notify: starttomcat

- name:  Install Admin Packages
  yum:
   name: "{{ item }}"
   state: present
  with_items:
    - tomcat-webapps
    - tomcat-admin-webapps
    
- name: copy tom user file into all nodes
  template:
   src: templates/mytomuser.j2
   dest: /usr/share/tomcat/conf/tomcat-users.xml
  notify: restarttomcat

- name: i want to deploy ravi java war file into webapps  
  get_url:
   url: https://raviwebapp.s3.amazonaws.com/raviLogin.war
   dest: /usr/share/tomcat/webapps/raviLogin.war
   force_basic_auth: yes
