---
# tasks file for myubunturole
- name: install tomcat8
  apt:
   name: tomcat8
   state: present

- name: tomcat8 status
  service: 
   name: tomcat8
   state: started

- name:  copy myubuntuconfig file into all nodes
  template:
   src:  templates/myubuntuconfig.j2
   dest: /var/lib/tomcat8/conf/server.xml
    
- name: copy ubuntu user file into all nodes
  template:
   src: templates/myubuntuuser.j2
   dest: /var/lib/tomcat8/conf/tomcat-users.xml
  notify: restart tomcat8

- name: install tomcat8-docs
  apt:
   name: tomcat8-docs
   state: present

- name: install tomcat8-examples
  apt:
   name: tomcat8-examples
   state: present

- name: install tomcat8-admin
  apt:
   name: tomcat8-admin
   state: present
  notify: restart tomcat8

- name: to enable 8080 port
  command:
   name: ufw allow 8080
   state: started
      
- name: i want to deploy ravi java war file into webapps  
  get_url:
   url: https://raviwebapp.s3.amazonaws.com/raviLogin.war
   dest: /usr/share/tomcat/webapps/raviLogin.war
   force_basic_auth: yes  
